CREATE TABLE boards (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(400) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    board_status VARCHAR(40) NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);